// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlI2T-FSH0Ln2xF3vACTrZmXbnNfeSG4s',
    appId: '1:976105632132:web:25e363483f9fcc6738edd1',
    messagingSenderId: '976105632132',
    projectId: 'qr-ledger',
    authDomain: 'qr-ledger.firebaseapp.com',
    storageBucket: 'qr-ledger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTvS799RpITnK8oUOUS7bGlrOkAtqraWk',
    appId: '1:976105632132:android:7d811effab2c49e338edd1',
    messagingSenderId: '976105632132',
    projectId: 'qr-ledger',
    storageBucket: 'qr-ledger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7wwLrvF43m5FgVSmzbDcx8Rkh3X0ANM',
    appId: '1:976105632132:ios:a14a31db5c06b9a038edd1',
    messagingSenderId: '976105632132',
    projectId: 'qr-ledger',
    storageBucket: 'qr-ledger.firebasestorage.app',
    iosBundleId: 'com.example.ledger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7wwLrvF43m5FgVSmzbDcx8Rkh3X0ANM',
    appId: '1:976105632132:ios:a14a31db5c06b9a038edd1',
    messagingSenderId: '976105632132',
    projectId: 'qr-ledger',
    storageBucket: 'qr-ledger.firebasestorage.app',
    iosBundleId: 'com.example.ledger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlI2T-FSH0Ln2xF3vACTrZmXbnNfeSG4s',
    appId: '1:976105632132:web:f1279ce82ed7ee0f38edd1',
    messagingSenderId: '976105632132',
    projectId: 'qr-ledger',
    authDomain: 'qr-ledger.firebaseapp.com',
    storageBucket: 'qr-ledger.firebasestorage.app',
  );

}